
name: kgm # you probably want to 'snapcraft register <kgm>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: KGM beta. Modding tool for Renderware .Img files # 79 char long summary
description: |
 KGM (Img Factory) is a modding tool for Renderware engine based games that support .img archives.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
